### ISSUE TITLE
Saving does do anything

### ISSUE THREAD

**Issue by lpugin** [DDMAL/VerovioEditor#6]
What is saving supposed to do? Would it be possible to save the file locally?

**Comment by ahwitz** [comment]
Try meix.js at commit https://github.com/DDMAL/meix.js/commit/c13af540fba14117b2d95733e2af5701364e98f1 or later. It looks like the submodule hasn't been updated in the VerovioEditor repo for a while.

**Comment by ahwitz** [comment]
Resolved as of meeting yesterday with https://github.com/DDMAL/vida.js/commit/7ca3b5969b32ec23dbcb7c197762820c63ed1873.
